### PR TITLE
Converted TwitterLeaderboard.docx to markdown file

### PR DESCRIPTION
**Pull request by sfarmar**
connects to https://github.com/Particular/DeveloperEducation/issues/254

### CODE REVIEW

**Comment by YifatS** [comment]
@sfarmar @adamralph @mauroservienti : any further comments?

**Comment by adamralph** [comment]
I think we need to consider where we want our docs for HashBus to live. We already have a considerable amount of technical docs in the README.md. Do we want to centralise everything there?

**Comment by mauroservienti** [comment]
Maybe not in the readme but I like to have it centralized in the HashBus repo. We need to take into account that the links at the end are private.

**Comment by adamralph** [comment]
> We need to take into account that the links at the end are private.

Then IMHO they should not be present in this repo.

**Comment by adamralph** [comment]
Or, they should be made public.

**Comment by sfarmar** [comment]
I'll move it to DevEdu

**Comment by sfarmar** [comment]
moved to https://github.com/Particular/DeveloperEducation/pull/495

**Pull request closed without merging**
