### PR TITLE
switch to sane csproj

### PR DESCRIPTION
**Pull request by adamralph**

### CODE REVIEW

**Comment by adamralph** [comment]
I smoke tested everything and it seems fine.

**Comment by seanfarmar** [comment]
I'll try and pull this branch and review locally :-)

**Comment by adamralph** [comment]
@seanfarmar marking as WIP because I forgot to remove `packages.config`. I'll push a fixup shortly.

**Review by seanfarmar — DISMISSED** [review]
LGTM, smoke tests ok... 👍

**Review by seanfarmar — DISMISSED** [review]
Good catch @adamralph!

**Comment by adamralph** [comment]
Squashed.

**Review by seanfarmar — APPROVED** [review]

**Pull request merged**
